version: '3.8'

services:
  webhook:
    image: almir/webhook
    container_name: webhook-listener
    ports:
      - "8001:9000"
    volumes:
      - ./deploy.sh:/deploy.sh
      - ./entrypoint.sh:/entrypoint.sh
      - /opt/secrets/.env:/run/secrets.env:ro
      - ./hooks.template.json:/hooks.template.json:ro
      - ./generated_hooks.json:/generated_hooks.json
      - /opt/docker/homelab-config:/repos/homelab-config
    working_dir: /repos/homelab-config
    entrypoint: /entrypoint.sh
    restart: unless-stopped