version: '3'
services:
  git-auto-deploy:
    image: olipo186/git-auto-deploy
    container_name: git-auto-deploy
    ports:
      - "8001:8001"
    volumes:
      - ../:/opt/docker
      - ./conf.template.yaml:/app/conf.template.yaml
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped